name: pxt-deploy-static

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g pxt
          npm install

      - name: Fix old deps
        run: |
          npm install typescript@3.9.10 --save-dev
          npm install @types/ws@7.4.0 --save-dev

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          pxt staticpkg --githubpages
